### ISSUE TITLE
double definition of `make_command` in `common_definitions.jl`

### ISSUE THREAD

**Issue by jfb-h** [StanJulia/StanBase.jl#39]
On windows systems, the variable `make_command` currently gets assigned twice, once in `common_definitions.jl:20` and once in line 50 in the same file.

**Comment by goedman** [comment]
Hi @jfb-h 

Apologies for that. I clearly messed this up. I just updated master. Can you have a look?

Rob

**Comment by goedman** [comment]
By the way, in the docs I use right now @jfb-h to refer to you, if you would like to use another name (or both), please let me know.

**Comment by jfb-h** [comment]
That's fine, thanks for the mention! Everything works now when I specify ` ENV["JULIA_CMDSTAN_HOME"]` instead of  `ENV["CMDSTAN"]` as mentioned in the other issue.
