### ISSUE TITLE
M1 mac issue with `get_cmdstan_home`

### ISSUE THREAD

**Issue by alexpkeil1** [StanJulia/StanBase.jl#40]
Hi, I'm trying to get the following example from Stan.jl to work. I'm using Julia 1.7.0 on an M1-based mac (13" mbp). I've tried this using the ARM-based binary as well as building from source.

Example:
```
ENV["CMDSTAN"] = expanduser("~/repo/cmdstan/")

using StanSample

bernoullimodel = "
data { 
  int<lower=1> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
  y ~ bernoulli(theta);
}
";

observed_data = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

SampleModel("bernoulli", bernoullimodel)
```

This results in the following error

```
/var/folders/7m/p1ykw_197cq_w48wmjq7wwh00000gp/T/jl_YxcohI/bernoulli.stan updated.
ERROR: MethodError: no method matching get(::StanBase.var"#1#2", ::Base.EnvDict, ::Nothing)
Closest candidates are:
  get(::Union{Function, Type}, ::IdDict{K, V}, ::Any) where {K, V} at ~/julia/usr/share/julia/base/iddict.jl:166
  get(::Union{Function, Type}, ::Base.Pairs, ::Any) at ~/julia/usr/share/julia/base/iterators.jl:261
  get(::Union{Function, Type}, ::Dict{K, V}, ::Any) where {K, V} at ~/julia/usr/share/julia/base/dict.jl:528
  ...
Stacktrace:
 [1] get_cmdstan_home()
   @ StanBase ~/.julia/packages/StanBase/0h8Sg/src/common/cmdstan_home.jl:19
 [2] SampleModel(name::String, model::String, tmpdir::String)
   @ StanSample ~/.julia/packages/StanSample/aHr3T/src/stanmodel/SampleModel.jl:96
 [3] top-level scope
   @ REPL[79]:1

```

I was unable to resolve on my own - I had previously had similar examples working on Non-ARM based Julia v1.7.0, but I was unable to reproduce that success with a fresh install.

**Comment by goedman** [comment]
Hi Alex,

Thanks for the report!

Recently I have made a few changes which might have caused this issue. Moving to M1 (as I also recently did) is also a bit tricky but I don't think that is the issue here.

Can you let me know which versions of packages are installed when you run above example? I have:
```
(StanSample) pkg> st
     Project StanSample v5.2.0
      Status `~/.julia/dev/StanSample/Project.toml`
  [336ed68f] CSV v0.9.11
  [a93c6f00] DataFrames v1.3.0
  [ffbed154] DocStringExtensions v0.8.6
  [0987c9cc] MonteCarloMeasurements v1.0.3
  [d9ec5142] NamedTupleTools v0.13.7
  [bac558e1] OrderedCollections v1.4.1
  [d96e819e] Parameters v0.12.3
  [ae029012] Requires v1.1.3
  [d0ee94f6] StanBase v3.2.0
  [9713c8f3] StanDump v0.2.0
  [ab02a1b2] TableOperations v1.2.0
  [bd369af6] Tables v1.6.0
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [9a3f8284] Random
  [4ec0a83e] Unicode
```

And also the settings of `ENV["CMDSTAN"]` and `ENV["JULIA_CMDSTAN_HOME"]`?

Do you run the arm version of Julia? Did you re-build Stan's cmdstan-2-28.2 (or install using conda)?

AS I said above, I think your problem is in my changes as it points to `get_cmdstan_home()`.

Rob

**Comment by goedman** [comment]
@alexpkeil1  I just pushed an update for StanSample.jl. Would you mind trying that version (v5.2.1)?

**Comment by goedman** [comment]
If you build Stan's cmdstan from source, you need the arm version of Julia.

**Comment by alexpkeil1** [comment]
I removed the old StanSample directory, re-installed StanSample.jl, and it's working again. Thank you!

Edited the original example to include the setting of ENV["CMDSTAN"]
